name: CI/CD to Google Cloud Run
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: 'beta'

      - name: Authenticate Docker with Artifact Registry
        run: |
          REGION="${{ secrets.GCP_REGION }}"
          gcloud auth configure-docker "${REGION}-docker.pkg.dev"

      - name: Build and Push Docker Image
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          GCP_REGION: ${{ secrets.GCP_REGION }}
          ARTIFACT_REPO_NAME: ${{ secrets.ARTIFACT_REPO_NAME }}
          CLOUD_RUN_SERVICE: ${{ secrets.CLOUD_RUN_SERVICE }}
        run: |
          IMAGE_URI="${GCP_REGION}-docker.pkg.dev/${GCP_PROJECT_ID}/${ARTIFACT_REPO_NAME}/${CLOUD_RUN_SERVICE}:${GITHUB_SHA}"
          echo "Using image URI: $IMAGE_URI"
          docker build -t "$IMAGE_URI" .
          docker push "$IMAGE_URI"

      - name: Deploy to Cloud Run
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          GCP_REGION: ${{ secrets.GCP_REGION }}
          CLOUD_RUN_SERVICE: ${{ secrets.CLOUD_RUN_SERVICE }}
          ARTIFACT_REPO_NAME: ${{ secrets.ARTIFACT_REPO_NAME }}
        run: |
          IMAGE_URI="${GCP_REGION}-docker.pkg.dev/${GCP_PROJECT_ID}/${ARTIFACT_REPO_NAME}/${CLOUD_RUN_SERVICE}:${GITHUB_SHA}"
          echo "Deploying image: $IMAGE_URI"
          gcloud run deploy "${CLOUD_RUN_SERVICE}" \
            --image "$IMAGE_URI" \
            --region "${GCP_REGION}" \
            --platform managed \
            --allow-unauthenticated \
            --project "${GCP_PROJECT_ID}"
